#:schema node_modules/wrangler/config-schema.json
name = "edtech-dynamic"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "MY_ASSETS"
pages_build_output_dir = ".next"
